---
- hosts: all
  become: yes

  tasks:

    - copy:
         content: "simple text file"
         dest: "/tmp/fab_was_here"
    # this is for all servers
    #- name: Changing /etc/resolv.conf search configuration
    #  lineinfile:
    #    dest: /tmp/resolv.conf
    #    regexp: '^search'
    #    line: 'search fab'
